const ADD_USER = 'ADD_USER';
const UPDATE_USER = 'UPDATE_USER';
const TOGGLE_USER = 'TOGGLE_USER';
const DELETE_USER = 'DELETE_USER';


exports.ADD_USER = ADD_USER;
exports.UPDATE_USER = UPDATE_USER;
exports.TOGGLE_USER = TOGGLE_USER;
exports.DELETE_USER = DELETE_USER;